# Generated by Django 5.2 on 2025-04-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Pagador')),
                ('tipo', models.CharField(choices=[('crédito', 'Crédito'), ('débito', 'Débito'), ('pix', 'PIX'), ('dinheiro', 'Dinheiro')], max_length=20, verbose_name='Tipo de Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pagamento')),
            ],
        ),
    ]
