# Generated by Django 5.2 on 2025-06-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notafiscal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotaFiscal',
        ),
    ]
